/*
 * This source file was generated by the Gradle 'init' task
 */
package my.backend

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class AppTest {
    @Test
    fun contextLoads() {
        // This test simply verifies that the Spring Boot application context loads successfully
    }
}
